var actions = {
	INITIALIZE_STATE: 'INITIALIZE_STATE',
	REMOVE_STATE: 'REMOVE_STATE',
	SET_SERVER_DATA: 'SET_SERVER_DATA',
	SET_PENDING_OP: 'SET_PENDING_OP',
	PUSH_PENDING_STATE: 'PUSH_PENDING_STATE',
	POP_PENDING_STATE: 'POP_PENDING_STATE',
	MERGE_FIRST_PENDING_STATE: 'MERGE_FIRST_PENDING_STATE',
	ESTIMATE_ATTRIBUTE: 'ESTIMATE_ATTRIBUTE',
	ESTIMATE_ATTRIBUTES: 'ESTIMATE_ATTRIBUTES',
	COMMIT_SERVER_CHANGES: 'COMMIT_SERVER_CHANGES',
	ENQUEUE_TASK: 'ENQUEUE_TASK'
}

export function parse(state = {}, action) {
	return state;
}