name: release-manual-docs
on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        description: 'Version tag:'
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  docs-publish:
    if: github.event.inputs.tag != ''
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - name: Generate Docs
        run: |
          npm ci
          npm run release_docs
        env:
          SOURCE_TAG: ${{ github.event.inputs.tag }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
